# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "BlockShop"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# Template engine
template: "template_toolkit"

# SQLite Database file
database: "db/shop.sqlite"

# Number of locker doors
doors: "8"

# Zcash type of address. One of ["sprout", "sapling"]
# https://zcash-rpc.github.io/z_getnewaddress.html
zcash_type: sapling

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"